apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::227071492203:role/eksctl-eksctl-demo-nodegroup-ng-5-NodeInstanceRole-14U0DIZBTVMS
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::227071492203:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-07-26T07:01:43Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1746"
  uid: dcbda69a-0a5f-4b6a-bad4-9704f4249326
